# prevent multiple inclusion
if(_ament_cmake_target_dependencies_CONFIG_INCLUDED)
  return()
endif()
set(_ament_cmake_target_dependencies_CONFIG_INCLUDED TRUE)

set(ament_cmake_target_dependencies_FOUND TRUE)

macro(ament_target_dependencies target)
  # Extract link interface modifier if present (PUBLIC | PRIVATE | INTERFACE)
  set(has_modifier FALSE)
  set(modifier "")
  set(deps "")
  foreach(arg ${ARGN})
    if(arg STREQUAL "PUBLIC" OR arg STREQUAL "PRIVATE" OR arg STREQUAL "INTERFACE")
      set(modifier ${arg})
      set(has_modifier TRUE)
    else()
      list(APPEND deps ${arg})
    endif()
  endforeach()

  foreach(dep ${deps})
    find_package(${dep} REQUIRED)
    if(TARGET ${dep}::${dep})
      if(has_modifier)
        target_link_libraries(${target} ${modifier} ${dep}::${dep})
      else()
        target_link_libraries(${target} ${dep}::${dep})
      endif()
    else()
      if(has_modifier)
        target_link_libraries(${target} ${modifier} ${${dep}_LIBRARIES})
        target_include_directories(${target} ${modifier} ${${dep}_INCLUDE_DIRS})
      else()
        target_link_libraries(${target} ${${dep}_LIBRARIES})
        target_include_directories(${target} PUBLIC ${${dep}_INCLUDE_DIRS})
      endif()
    endif()
  endforeach()
endmacro()
